# Generated by Django 5.1.5 on 2025-02-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
